"""Tests for PR-3: V5 staged execution engine (boundary/magnetic/tower_mill/
flotation/dcs/lab/label).

Covers the PR-3 requirements:
- engine can run 3–10 timesteps
- every stage has at least one output variable update
- manual_promoted magnetic formulas (B_eff, capture_j, E_pulse, E_ring,
  E_level, Entr, R_hm_j, conc_j, tail_j) are executed
- lab_tm_overflow_tfe and lab_mag_mixed_conc_tfe are generated by
  lab_sample_template (not bare external inputs)
- y_fx_xin* variables are NOT generated before the label step
"""
from __future__ import annotations

import math
import pytest

from sim.v5.spec_loader import load_spec, FormulaRegistry
from sim.v5.execution_scheduler import ExecutionScheduler
from sim.v5.engine import (
    V5SimulationEngine,
    DEFAULT_PARAMS,
    LABEL_ONLY_LHS,
)
from sim.v5.helpers import (
    clip,
    sigmoid,
    thermal_derate,
    meas,
    lab_sample_template,
    ffill_reported,
    build_helpers_namespace,
)
from sim.v5.formula_evaluator import (
    FormulaEvaluator,
    FormulaEvaluationError,
    UnsupportedFormulaError,
    preprocess_rhs,
)
from sim.v5.state_store import StateStore


# ---------------------------------------------------------------------------
# Shared fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def registry() -> FormulaRegistry:
    return load_spec()


@pytest.fixture(scope="module")
def engine_after_5_steps(registry) -> V5SimulationEngine:
    """An engine that has already run 5 timesteps."""
    eng = V5SimulationEngine(registry)
    eng.run(5)
    return eng


# ---------------------------------------------------------------------------
# Helper function tests
# ---------------------------------------------------------------------------


class TestHelpers:
    def test_clip_within_bounds(self):
        assert clip(0.5, 0.0, 1.0) == pytest.approx(0.5)

    def test_clip_below_lo(self):
        assert clip(-1.0, 0.0, 1.0) == pytest.approx(0.0)

    def test_clip_above_hi(self):
        assert clip(2.0, 0.0, 1.0) == pytest.approx(1.0)

    def test_sigmoid_zero(self):
        assert sigmoid(0.0) == pytest.approx(0.5)

    def test_sigmoid_large_positive(self):
        assert sigmoid(100.0) == pytest.approx(1.0, abs=1e-6)

    def test_sigmoid_large_negative(self):
        assert sigmoid(-100.0) == pytest.approx(0.0, abs=1e-6)

    def test_thermal_derate_nominal(self):
        # At T_ref temperature, derate should be 1.0
        assert thermal_derate(50.0, T_ref=50.0) == pytest.approx(1.0)

    def test_thermal_derate_high_temp(self):
        # Higher temperature → derate < 1.0
        assert thermal_derate(100.0, T_ref=50.0, alpha=0.002) < 1.0

    def test_meas_passthrough(self):
        assert meas(42.5) == pytest.approx(42.5)

    def test_meas_none_returns_nan(self):
        assert math.isnan(meas(None))

    def test_ffill_reported_valid(self):
        assert ffill_reported(0.65) == pytest.approx(0.65)

    def test_ffill_reported_nan(self):
        assert math.isnan(ffill_reported(float("nan")))

    def test_ffill_reported_none(self):
        assert math.isnan(ffill_reported(None))

    def test_lab_sample_template_returns_numeric(self):
        # With step_time >= report_time, should return a numeric value
        result = lab_sample_template(
            x_val=0.60,
            sample_time=0.0,
            report_time=0.0,
            sigma_sampling=0.001,
            sigma_assay=0.001,
            step_time=0.0,
        )
        assert isinstance(result, float)
        assert not math.isnan(result)
        # Should be close to 100 * 0.60 = 60 pct
        assert abs(result - 60.0) < 1.0

    def test_lab_sample_template_not_yet_reported(self):
        # step_time < report_time → NaN
        result = lab_sample_template(
            x_val=0.60,
            sample_time=0.0,
            report_time=3600.0,
            sigma_sampling=0.001,
            sigma_assay=0.001,
            step_time=0.0,
        )
        assert math.isnan(result)

    def test_build_helpers_namespace_contains_clip(self):
        ns = build_helpers_namespace()
        assert "clip" in ns
        assert ns["clip"](0.5, 0.0, 1.0) == pytest.approx(0.5)

    def test_build_helpers_namespace_contains_sigmoid(self):
        ns = build_helpers_namespace()
        assert "sigmoid" in ns

    def test_build_helpers_namespace_contains_lab_sample_template(self):
        ns = build_helpers_namespace()
        assert "lab_sample_template" in ns

    def test_build_helpers_namespace_contains_ifelse(self):
        ns = build_helpers_namespace()
        assert "ifelse" in ns
        assert ns["ifelse"](True, 1.0, 0.0) == pytest.approx(1.0)
        assert ns["ifelse"](False, 1.0, 0.0) == pytest.approx(0.0)

    def test_build_helpers_namespace_contains_standardized(self):
        ns = build_helpers_namespace()
        assert "standardized" in ns


# ---------------------------------------------------------------------------
# RHS preprocessing tests
# ---------------------------------------------------------------------------


class TestPreprocessRhs:
    def test_caret_replaced(self):
        result = preprocess_rhs("x^2")
        assert result == "x**2"

    def test_nan_string(self):
        assert preprocess_rhs("NaN") == "float('nan')"

    def test_empty_string(self):
        assert preprocess_rhs("") == "float('nan')"

    def test_no_change_needed(self):
        result = preprocess_rhs("clip(x, 0, 1)")
        assert result == "clip(x, 0, 1)"

    def test_exponentiation_in_formula(self):
        result = preprocess_rhs("exp(-((f_pul-f_pul_opt)/sigma_pul)^2)")
        assert "**2" in result
        assert "^" not in result


# ---------------------------------------------------------------------------
# FormulaEvaluator tests
# ---------------------------------------------------------------------------


class TestFormulaEvaluator:
    def test_evaluates_simple_expression(self, registry):
        evaluator = FormulaEvaluator(params={"B_max": 1.5, "I_exc": 10.0, "I_ref": 5.0,
                                             "T_coil": 25.0, "eps": 1e-10, "dt": 60.0})
        store = StateStore()
        formula = registry.by_lhs["B_eff"]
        result = evaluator.eval_formula(formula, store)
        assert isinstance(result, float)
        assert result > 0.0

    def test_b_eff_value_range(self, registry):
        """B_eff should be in (0, B_max] given sensible parameters."""
        evaluator = FormulaEvaluator(
            params={**DEFAULT_PARAMS, "B_max": 1.5, "I_exc": 10.0, "I_ref": 5.0, "T_coil": 25.0}
        )
        store = StateStore()
        formula = registry.by_lhs["B_eff"]
        result = evaluator.eval_formula(formula, store)
        assert 0.0 < result <= 1.5

    def test_unsupported_formula_raises(self, registry):
        """Formula with unknown name raises UnsupportedFormulaError."""
        evaluator = FormulaEvaluator(params={"dt": 60.0})
        store = StateStore()
        formula = registry.by_lhs["B_eff"]  # needs B_max, I_exc, etc.
        with pytest.raises(UnsupportedFormulaError):
            evaluator.eval_formula(formula, store)

    def test_previous_state_used(self, registry):
        """Evaluator reads X_prev from store.previous when formula references X_prev."""
        evaluator = FormulaEvaluator(params={**DEFAULT_PARAMS})
        store = StateStore()
        # T_coil = T_coil_ss + (T_coil_prev - T_coil_ss)*exp(-dt/tau_coil)
        # T_coil_prev comes from store.previous["T_coil"]
        store.set("T_coil", 30.0)
        store.advance()
        formula = registry.by_lhs["T_coil"]
        result = evaluator.eval_formula(formula, store)
        assert isinstance(result, float)
        # T_coil should be between T_coil_ss (25) and previous T_coil (30)
        assert 24.0 <= result <= 31.0

    def test_nan_rhs_returns_nan(self, registry):
        evaluator = FormulaEvaluator(params={**DEFAULT_PARAMS})
        store = StateStore()
        formula = registry.by_lhs["lab_var"]  # rhs=NaN
        result = evaluator.eval_formula(formula, store)
        assert math.isnan(result)


# ---------------------------------------------------------------------------
# Engine initialisation tests
# ---------------------------------------------------------------------------


class TestV5EngineInit:
    def test_engine_constructs(self, registry):
        engine = V5SimulationEngine(registry)
        assert engine.step_count == 0
        assert engine.step_time == 0.0

    def test_engine_store_empty_before_step(self, registry):
        engine = V5SimulationEngine(registry)
        assert len(engine.store.current) == 0

    def test_initialize_sets_state(self, registry):
        engine = V5SimulationEngine(registry)
        engine.initialize({"my_var": 42.0})
        assert engine.store.get("my_var") == pytest.approx(42.0)

    def test_label_only_lhs_contains_y_fx_xin(self):
        assert "y_fx_xin_s" in LABEL_ONLY_LHS
        assert "y_fx_xin_s_true" in LABEL_ONLY_LHS

    def test_engine_has_all_stages(self, registry):
        engine = V5SimulationEngine(registry)
        stages = engine.all_stage_names()
        for expected in ["boundary", "magnetic", "tower_mill", "flotation", "dcs", "lab", "label"]:
            assert expected in stages


# ---------------------------------------------------------------------------
# Engine step tests
# ---------------------------------------------------------------------------


class TestV5EngineStep:
    def test_single_step_increments_counter(self, registry):
        engine = V5SimulationEngine(registry)
        engine.step()
        assert engine.step_count == 1

    def test_step_increments_time(self, registry):
        engine = V5SimulationEngine(registry)
        engine.step()
        assert engine.step_time == pytest.approx(60.0)

    def test_run_3_steps(self, registry):
        engine = V5SimulationEngine(registry)
        engine.run(3)
        assert engine.step_count == 3

    def test_run_10_steps(self, registry):
        engine = V5SimulationEngine(registry)
        engine.run(10)
        assert engine.step_count == 10

    def test_run_produces_executed_formulas(self, registry):
        engine = V5SimulationEngine(registry)
        engine.run(3)
        assert len(engine.executed_lhs) > 0

    def test_skipped_formulas_are_tracked_not_silent(self, registry):
        """Formulas that fail are tracked in engine.skipped (not silently dropped)."""
        engine = V5SimulationEngine(registry)
        engine.run(3)
        # skipped may or may not be non-empty, but if formulas fail they MUST be tracked
        for lhs, err_msg in engine.skipped.items():
            assert isinstance(err_msg, str) and len(err_msg) > 0


# ---------------------------------------------------------------------------
# Stage output tests
# ---------------------------------------------------------------------------


class TestV5StageCoverage:
    """Every stage must produce at least one output variable update."""

    @pytest.mark.parametrize("stage", [
        "boundary", "magnetic", "tower_mill", "flotation", "dcs", "lab", "label",
    ])
    def test_stage_has_output_variables(self, engine_after_5_steps, stage):
        outputs = engine_after_5_steps.stage_outputs(stage)
        assert len(outputs) > 0, (
            f"Stage '{stage}' has no output variable updates after 5 timesteps. "
            f"At least one formula must succeed."
        )

    def test_boundary_stage_has_ore_variables(self, engine_after_5_steps):
        outputs = engine_after_5_steps.stage_outputs("boundary")
        # At least one of the boundary ore/feed variables should be updated
        boundary_candidates = {"M_wet_i", "C_i", "M_solid_i", "TFe_i", "Fe_mag_i"}
        assert boundary_candidates & outputs, (
            f"No expected boundary variables in {outputs}"
        )

    def test_magnetic_stage_has_promoted_variables(self, engine_after_5_steps):
        outputs = engine_after_5_steps.stage_outputs("magnetic")
        promoted = {"B_eff", "E_pulse", "E_ring", "E_level", "Entr",
                    "R_hm_j", "capture_j", "conc_j", "tail_j"}
        assert promoted.issubset(outputs), (
            f"Missing magnetic promoted variables in outputs. "
            f"Present: {promoted & outputs}, Missing: {promoted - outputs}"
        )

    def test_tower_mill_stage_has_feed_variable(self, engine_after_5_steps):
        outputs = engine_after_5_steps.stage_outputs("tower_mill")
        assert "C_feed" in outputs or len(outputs) > 0

    def test_lab_stage_generates_lab_samples(self, engine_after_5_steps):
        outputs = engine_after_5_steps.stage_outputs("lab")
        assert "lab_tm_overflow_tfe" in outputs
        assert "lab_mag_mixed_conc_tfe" in outputs

    def test_label_stage_has_y_fx_xin(self, engine_after_5_steps):
        outputs = engine_after_5_steps.stage_outputs("label")
        assert "y_fx_xin_s" in outputs
        assert "y_fx_xin_s_true" in outputs


# ---------------------------------------------------------------------------
# Magnetic stage: manual_promoted formulas
# ---------------------------------------------------------------------------


class TestV5MagneticStage:
    """manual_promoted magnetic formulas must all be executed."""

    _PROMOTED = [
        "B_eff",
        "capture_j",
        "E_pulse",
        "E_ring",
        "E_level",
        "Entr",
        "R_hm_j",
        "conc_j",
        "tail_j",
    ]

    @pytest.mark.parametrize("lhs", _PROMOTED)
    def test_promoted_formula_executed(self, engine_after_5_steps, lhs):
        """manual_promoted formula is in executed_lhs after running."""
        assert lhs in engine_after_5_steps.executed_lhs, (
            f"manual_promoted formula '{lhs}' was NOT executed by the engine."
        )

    @pytest.mark.parametrize("lhs", _PROMOTED)
    def test_promoted_formula_in_store(self, engine_after_5_steps, lhs):
        """manual_promoted formula result is in the StateStore."""
        assert engine_after_5_steps.store.has(lhs), (
            f"manual_promoted formula '{lhs}' result is not in the StateStore."
        )

    def test_b_eff_positive(self, engine_after_5_steps):
        assert engine_after_5_steps.store.get("B_eff") > 0.0

    def test_capture_j_in_0_1(self, engine_after_5_steps):
        val = engine_after_5_steps.store.get("capture_j")
        assert 0.0 <= val <= 1.0

    def test_e_pulse_in_0_1(self, engine_after_5_steps):
        val = engine_after_5_steps.store.get("E_pulse")
        assert 0.0 <= val <= 1.0

    def test_e_ring_in_0_1(self, engine_after_5_steps):
        val = engine_after_5_steps.store.get("E_ring")
        assert 0.0 <= val <= 1.0

    def test_e_level_in_0_1(self, engine_after_5_steps):
        val = engine_after_5_steps.store.get("E_level")
        assert 0.0 <= val <= 1.0

    def test_all_magnetic_promoted_in_registry(self, registry):
        """All required promoted formulas exist in the V5 registry."""
        promoted_lhs = {f.lhs for f in registry.formulas if f.status == "manual_promoted"}
        required = set(self._PROMOTED)
        assert required.issubset(promoted_lhs), (
            f"Missing from registry manual_promoted: {required - promoted_lhs}"
        )

    def test_magnetic_promoted_formulas_in_stage(self, registry):
        """All required promoted formulas are in the magnetic stage."""
        mag_lhs = {
            f.lhs for f in registry.formulas
            if f.stage == "magnetic" and f.status == "manual_promoted"
        }
        assert set(self._PROMOTED).issubset(mag_lhs)


# ---------------------------------------------------------------------------
# Lab stage: lab_sample_template
# ---------------------------------------------------------------------------


class TestV5LabStage:
    """Lab variables must be generated by lab_sample_template."""

    def test_lab_tm_overflow_tfe_generated(self, engine_after_5_steps):
        """lab_tm_overflow_tfe is set in the store (generated by lab stage)."""
        assert engine_after_5_steps.store.has("lab_tm_overflow_tfe"), (
            "lab_tm_overflow_tfe is not in the StateStore after running."
        )

    def test_lab_mag_mixed_conc_tfe_generated(self, engine_after_5_steps):
        """lab_mag_mixed_conc_tfe is set in the store (generated by lab stage)."""
        assert engine_after_5_steps.store.has("lab_mag_mixed_conc_tfe"), (
            "lab_mag_mixed_conc_tfe is not in the StateStore after running."
        )

    def test_lab_tm_overflow_tfe_in_lab_stage_outputs(self, engine_after_5_steps):
        """lab_tm_overflow_tfe is listed as a lab stage output — not a raw external input."""
        assert "lab_tm_overflow_tfe" in engine_after_5_steps.stage_outputs("lab")

    def test_lab_mag_mixed_conc_tfe_in_lab_stage_outputs(self, engine_after_5_steps):
        """lab_mag_mixed_conc_tfe is listed as a lab stage output."""
        assert "lab_mag_mixed_conc_tfe" in engine_after_5_steps.stage_outputs("lab")

    def test_lab_tm_overflow_tfe_formula_uses_lab_sample_template(self, registry):
        """The formula for lab_tm_overflow_tfe calls lab_sample_template in its RHS."""
        formula = registry.by_lhs.get("lab_tm_overflow_tfe")
        assert formula is not None, "lab_tm_overflow_tfe not in registry"
        assert "lab_sample_template" in formula.rhs

    def test_lab_mag_mixed_conc_tfe_formula_uses_lab_sample_template(self, registry):
        """The formula for lab_mag_mixed_conc_tfe calls lab_sample_template in its RHS."""
        formula = registry.by_lhs.get("lab_mag_mixed_conc_tfe")
        assert formula is not None, "lab_mag_mixed_conc_tfe not in registry"
        assert "lab_sample_template" in formula.rhs

    def test_lab_tm_overflow_tfe_not_in_initial_state(self, registry):
        """lab_tm_overflow_tfe is absent from the store before the lab stage runs."""
        engine = V5SimulationEngine(registry)
        # After construction and before any steps, lab vars should not be computed
        # (they are in DEFAULT_PARAMS as NaN, but the store is empty)
        assert not engine.store.has("lab_tm_overflow_tfe")

    def test_lab_values_are_numeric_after_steps(self, engine_after_5_steps):
        """Lab values are finite floats (not NaN) given immediate report_time=0."""
        val = engine_after_5_steps.store.get("lab_tm_overflow_tfe")
        assert isinstance(val, float)
        # With report_time=0 and sigma~0.001, value should be near 60 pct TFe.
        # NaN is acceptable only if report_time has not yet been reached.
        if not math.isnan(val):
            assert 55.0 < val < 65.0

    def test_lab_stage_not_generating_external_inputs_directly(self, registry):
        """lab_tm_overflow_tfe is NOT in the external_inputs registry (it's a derived lab var)."""
        ext_parents = {row.parent for row in registry.external_inputs}
        # lab_tm_overflow_tfe is computed by lab_sample_template, not an external input
        assert "lab_tm_overflow_tfe" not in ext_parents


# ---------------------------------------------------------------------------
# Label stage: y_fx_xin must NOT appear before label step
# ---------------------------------------------------------------------------


class TestV5LabelStage:
    """y_fx_xin* variables must only appear in the label step."""

    def test_y_fx_xin_in_label_stage_outputs(self, engine_after_5_steps):
        """y_fx_xin_s is produced by the label stage."""
        assert "y_fx_xin_s" in engine_after_5_steps.stage_outputs("label")

    def test_y_fx_xin_true_in_label_stage_outputs(self, engine_after_5_steps):
        """y_fx_xin_s_true is produced by the label stage."""
        assert "y_fx_xin_s_true" in engine_after_5_steps.stage_outputs("label")

    def test_y_fx_xin_NOT_in_flotation_stage_outputs(self, engine_after_5_steps):
        """y_fx_xin vars must NOT be in flotation stage outputs."""
        flotation_outputs = engine_after_5_steps.stage_outputs("flotation")
        assert "y_fx_xin_s" not in flotation_outputs, (
            "y_fx_xin_s was incorrectly produced in the flotation stage."
        )
        assert "y_fx_xin_s_true" not in flotation_outputs, (
            "y_fx_xin_s_true was incorrectly produced in the flotation stage."
        )

    def test_y_fx_xin_not_in_store_before_label_runs(self, registry):
        """Introspection: after flotation but before label step, y_fx_xin must not be set."""
        engine = V5SimulationEngine(registry)
        # Manually advance and run only up to flotation stage
        engine.store.advance()
        engine.step_time += engine._dt
        engine.step_count += 1

        stages_before_label = [
            s for s in engine.all_stage_names() if s != "label"
        ]
        for stage in stages_before_label:
            engine._run_stage(stage)

        # At this point the label stage has not run — y_fx_xin must NOT be set
        assert not engine.store.has("y_fx_xin_s"), (
            "y_fx_xin_s was set before the label stage ran."
        )
        assert not engine.store.has("y_fx_xin_s_true"), (
            "y_fx_xin_s_true was set before the label stage ran."
        )

    def test_y_fx_xin_present_after_label_step(self, registry):
        """After the label stage runs, y_fx_xin vars must be in the store."""
        engine = V5SimulationEngine(registry)
        engine.store.advance()
        engine.step_time += engine._dt
        engine.step_count += 1

        for stage in engine.all_stage_names():
            engine._run_stage(stage)

        # Now the label stage has run
        assert engine.store.has("y_fx_xin_s"), (
            "y_fx_xin_s was not set by the label stage."
        )
        assert engine.store.has("y_fx_xin_s_true"), (
            "y_fx_xin_s_true was not set by the label stage."
        )

    def test_y_fx_xin_s_value_in_0_1(self, engine_after_5_steps):
        """y_fx_xin_s (clipped output) should be in [0, 1]."""
        val = engine_after_5_steps.store.get("y_fx_xin_s")
        assert 0.0 <= val <= 1.0

    def test_y_fx_xin_s_true_matches_final_conc(self, engine_after_5_steps):
        """y_fx_xin_s_true = TFe(final_conc_s) should be a reasonable grade value."""
        val = engine_after_5_steps.store.get("y_fx_xin_s_true")
        # Should be a fraction (0–1 range), not NaN
        assert not math.isnan(val)
        assert 0.0 <= val <= 1.0

    def test_label_only_lhs_not_in_non_label_stages(self, engine_after_5_steps):
        """LABEL_ONLY_LHS vars must not appear in any non-label stage output set."""
        for stage in engine_after_5_steps.all_stage_names():
            if stage == "label":
                continue
            stage_out = engine_after_5_steps.stage_outputs(stage)
            for lhs in LABEL_ONLY_LHS:
                assert lhs not in stage_out, (
                    f"Label-only variable '{lhs}' found in non-label stage '{stage}'"
                )


# ---------------------------------------------------------------------------
# Execution order tests
# ---------------------------------------------------------------------------


class TestV5ExecutionOrder:
    def test_stage_order(self, registry):
        """Execution stages are: boundary -> magnetic -> tower_mill -> flotation -> dcs -> lab -> label."""
        engine = V5SimulationEngine(registry)
        stages = engine.all_stage_names()
        expected = ["boundary", "magnetic", "tower_mill", "flotation", "dcs", "lab", "label"]
        assert stages == expected

    def test_boundary_runs_before_magnetic(self, registry):
        """Boundary outputs are computed before magnetic formulas use them."""
        engine = V5SimulationEngine(registry)
        # Boundary sets M_wet_i; magnetic reads Q_feed etc.
        engine.run(1)
        assert engine.store.has("M_wet_i"), "M_wet_i not set by boundary stage"
        assert engine.store.has("B_eff"), "B_eff not set by magnetic stage"

    def test_lab_runs_before_label(self, registry):
        """Lab sample variables are available when the label stage runs."""
        engine = V5SimulationEngine(registry)
        engine.run(1)
        # After run, label stage should have y_fx_xin which depends on final_conc_s
        assert engine.store.has("y_fx_xin_s")

    def test_magnetic_before_tower_mill(self, registry):
        """Magnetic conc outputs (M_mag_conc_solid) feed tower mill if available."""
        engine = V5SimulationEngine(registry)
        engine.run(2)
        # Both stages should produce outputs
        assert len(engine.stage_outputs("magnetic")) > 0
        assert len(engine.stage_outputs("tower_mill")) > 0


# ---------------------------------------------------------------------------
# Registry cross-checks for PR-3 requirements
# ---------------------------------------------------------------------------


class TestV5RegistryCrossChecks:
    def test_y_fx_xin_tagged_flotation_in_csv(self, registry):
        """y_fx_xin_s and y_fx_xin_s_true are tagged flotation in the CSV (by design)."""
        for lhs in LABEL_ONLY_LHS:
            formula = registry.by_lhs[lhs]
            assert formula.stage == "flotation", (
                f"Expected y_fx_xin formula '{lhs}' to have stage='flotation' in CSV"
            )

    def test_label_stage_has_no_csv_formulas(self, registry):
        """label stage has no formulas in the CSV — engine adds them explicitly."""
        label_formulas = registry.by_stage.get("label", [])
        assert len(label_formulas) == 0

    def test_engine_label_formulas_are_y_fx_xin(self, registry):
        """The engine's label_formulas list contains exactly the LABEL_ONLY_LHS vars."""
        engine = V5SimulationEngine(registry)
        label_lhs = {f.lhs for f in engine._label_formulas}
        assert label_lhs == LABEL_ONLY_LHS

    def test_lab_formulas_in_lab_stage(self, registry):
        """lab_tm_overflow_tfe and lab_mag_mixed_conc_tfe are in the lab stage."""
        lab_lhs = {f.lhs for f in registry.by_stage.get("lab", [])}
        assert "lab_tm_overflow_tfe" in lab_lhs
        assert "lab_mag_mixed_conc_tfe" in lab_lhs

    def test_manual_promoted_in_magnetic_stage(self, registry):
        """All 9 required manual_promoted formulas are present in the magnetic stage."""
        required = {
            "B_eff", "capture_j", "E_pulse", "E_ring", "E_level",
            "Entr", "R_hm_j", "conc_j", "tail_j",
        }
        magnetic_promoted = {
            f.lhs
            for f in registry.by_stage.get("magnetic", [])
            if f.status == "manual_promoted"
        }
        assert required.issubset(magnetic_promoted)
